### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by Romern** [Romern/syncMyMoodle#124]
```
Run flake8 syncmymoodle
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/plugins/finder.py", line 291, in _load_plugin
    obj = plugin.entry_point.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.local/lib/python3.10/site-packages/bugbear.py", line 49, in <module>
    @attr.s(unsafe_hash=False)
TypeError: attrs() got an unexpected keyword argument 'unsafe_hash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/options/parse_args.py", line 42, in parse_args
    plugins = finder.load_plugins(raw_plugins, plugin_opts)
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/plugins/finder.py", line 365, in load_plugins
    return _classify_plugins(_import_plugins(plugins, opts), opts)
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/plugins/finder.py", line 307, in _import_plugins
    return [_load_plugin(p) for p in plugins]
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/plugins/finder.py", line 307, in <listcomp>
    return [_load_plugin(p) for p in plugins]
  File "/home/runner/.local/lib/python3.10/site-packages/flake8/plugins/finder.py", line 293, in _load_plugin
    raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "flake8-bugbear" due to attrs() got an unexpected keyword argument 'unsafe_hash'.
```

https://github.com/Romern/syncMyMoodle/actions/runs/10824777198/job/30032576313

**Comment by D-VR** [comment]
Seems to be because of https://github.com/PyCQA/flake8-bugbear/pull/486 and https://github.com/PyCQA/flake8-bugbear/pull/490

When bugbear gets a new release it will be resolved (attrs version is not compatible otherwise?)
Otherwise we could add a attrs requirement

**Comment by septatrix** [comment]
Or we could replace flake with ruff

**Comment by D-VR** [comment]
According to this, ruff even supports bugbear, so it would be a drop-in replacement

https://docs.astral.sh/ruff/faq/#how-does-ruffs-linter-compare-to-flake8

**Comment by D-VR** [comment]
The latest dev build succeeded so the underlying issue seems to have resolved itself without requiring action on or part
