### ISSUE TITLE
Gui crashes at startup

### ISSUE THREAD

**Issue by autoantwort** [Romern/syncMyMoodle#27]
When I start the app I get the following error:
```
ip-074:syncMyMoodle xx$ ./gui.py 
Traceback (most recent call last):
  File "/Users/xx/git_projekte/syncMyMoodle/./gui.py", line 947, in <module>
    app = SyncMyMoodleApp()
  File "/Users/xx/git_projekte/syncMyMoodle/./gui.py", line 940, in __init__
    frame = MainFrame(None)
  File "/Users/xx/git_projekte/syncMyMoodle/./gui.py", line 890, in __init__
    self.settings_tab = SettingsTab(notebook, self.smm)
  File "/Users/xx/git_projekte/syncMyMoodle/./gui.py", line 668, in __init__
    self.login_panel = SettingsTab.LoginPanel(self, self.smm)
  File "/Users/xx/git_projekte/syncMyMoodle/./gui.py", line 397, in __init__
    login_sizer.Add(
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/sizer.cpp(2168) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
```

**Comment by Romern** [comment]
Another Mac user had the same problem, recent wxPython versions seem to have problems: https://github.com/DeepLabCut/DeepLabCut/issues/682
They suggested using version 4.0.7.post2 (this is also the one I use).

**Comment by autoantwort** [comment]
Yes works now 👍 Cool Project!
