### ISSUE TITLE
Can not sync course 

### ISSUE THREAD

**Issue by autoantwort** [Romern/syncMyMoodle#28]
The first time I started the programm I got the following:
```
ip-074:syncMyMoodle xx$ ./syncMyMoodle.py 
Logging in...
Syncing file tree...
Syncing (VO) Compilerbau...
Traceback (most recent call last):
  File "/Users/xx/git_projekte/syncMyMoodle/./syncMyMoodle.py", line 555, in <module>
    smm.sync()
  File "/Users/xx/git_projekte/syncMyMoodle/./syncMyMoodle.py", line 264, in sync
    section_node = course_node.add_child(section["name"], section["id"], "Section")
TypeError: string indices must be integers
```
and if I rerun:
```
ip-074:syncMyMoodle xx$ ./syncMyMoodle.py 
Logging in...
Syncing file tree...
Traceback (most recent call last):
  File "/Users/xx/git_projekte/syncMyMoodle/./syncMyMoodle.py", line 555, in <module>
    smm.sync()
  File "/Users/xx/git_projekte/syncMyMoodle/./syncMyMoodle.py", line 239, in sync
    for course in self.get_all_courses():
  File "/Users/xx/git_projekte/syncMyMoodle/./syncMyMoodle.py", line 135, in get_all_courses
    return json.loads(resp.json()["responses"][0]["data"])
KeyError: 'responses'
```

**Comment by autoantwort** [comment]
It only happens with the course `(VO) Compilerbau`. If I remove the course from `selected_courses` everything works.

**Comment by Romern** [comment]
Compilerbau somehow sometimes throws exceptions on the server side. The error should now be catched: https://github.com/Romern/syncMyMoodle/commit/cf8753b4408c9f6bf593d75775e89c3daf8a0800
