### ISSUE TITLE
some embedded videos are not downloaded

### ISSUE THREAD

**Issue by HarHarLinks** [Romern/syncMyMoodle#56]
Lesson/Exercise Recordings of https://moodle.rwth-aachen.de/course/view.php?id=14908 (Spezielle Themen der Virtuellen Realität (VR II) (VU) [21ss-12.53694])

<details>
<summary>

```
./syncMyMoodle.py --courses https://moodle.rwth-aachen.de/course/view.php\?id\=14908 --verbose
```

</summary>

```
{
    "id": 142745,
    "name": "Lesson/Exercise Recordings",
    "visible": 1,
    "summary": "<p dir=\"ltr\" style=\"text-align: left;\"><div><div><p dir=\"ltr\">Each page features a player, which loads quite slowly. Just wait a few seconds for it to appear.</p></div></div></p>",
    "summaryformat": 1,
    "section": 1,
    "hiddenbynumsections": 0,
    "uservisible": true,
    "modules": [
        {
            "id": 597175,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=597175",
            "name": "Lesson 01 - Introduction",
            "instance": 43860,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 1,
                "timecompleted": 1619710133,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1457470/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1619417021,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1619417021,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 598698,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=598698",
            "name": "Lesson 02 - Applications",
            "instance": 43992,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 1,
                "timecompleted": 1619710134,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1459462/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1619417057,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1619417057,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 603818,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=603818",
            "name": "Lesson 03 - Navigation Pt. 1",
            "instance": 44444,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 1,
                "timecompleted": 1619710134,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1529135/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1620197686,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1620197686,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 604269,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=604269",
            "name": "Lesson 04 - Navigation Pt. 2",
            "instance": 44470,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 1,
                "timecompleted": 1619710135,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1529626/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1619702537,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1619702537,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 609189,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=609189",
            "name": "Lesson 05 - Navigation Pt. 3",
            "instance": 44979,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1535958/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1620197673,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1620197673,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 620451,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=620451",
            "name": "Lesson 06 - Navigation Pt. 4",
            "instance": 45990,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1549604/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1621411334,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1621411334,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 621146,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=621146",
            "name": "Lesson 07 - Haptics Pt. 1",
            "instance": 46059,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1550385/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1621439563,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1621439563,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 631970,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=631970",
            "name": "Lesson 07 - Haptics Pt. 2 &amp; Exercise 02",
            "instance": 47019,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1564122/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1623248421,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1623248421,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 627682,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=627682",
            "name": "Lesson 08 - Audio Rendering",
            "instance": 46552,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1559018/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1622573807,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1622573807,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 633908,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=633908",
            "name": "Lesson 09 - Audio Rendering Pt. 2",
            "instance": 47193,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1566381/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1623248130,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1623248130,
                "mimetypes": [],
                "repositorytype": ""
            }
        },
        {
            "id": 615466,
            "url": "https://moodle.rwth-aachen.de/mod/page/view.php?id=615466",
            "name": "Exercise 1 - Navigation",
            "instance": 45549,
            "visible": 1,
            "uservisible": true,
            "visibleoncoursepage": 1,
            "modicon": "https://moodle.rwth-aachen.de/theme/image.php/boost_campus_rwth/page/1623215512/icon",
            "modname": "page",
            "modplural": "Textseiten",
            "indent": 0,
            "onclick": "",
            "afterlink": null,
            "customdata": "\"\"",
            "noviewlink": false,
            "completion": 1,
            "completiondata": {
                "state": 0,
                "timecompleted": 0,
                "overrideby": null,
                "valueused": false
            },
            "contents": [
                {
                    "type": "file",
                    "filename": "index.html",
                    "filepath": "/",
                    "filesize": 0,
                    "fileurl": "https://moodle.rwth-aachen.de/webservice/pluginfile.php/1543654/mod_page/content/index.html?forcedownload=1",
                    "timecreated": null,
                    "timemodified": 1620811201,
                    "sortorder": 1,
                    "userid": null,
                    "author": null,
                    "license": null
                }
            ],
            "contentsinfo": {
                "filescount": 1,
                "filessize": 0,
                "lastmodified": 1620811201,
                "mimetypes": [],
                "repositorytype": ""
            }
        }
    ]
}
```

</details>

**Comment by Romern** [comment]
could you post the contents of the "Lesson 01 - Introduction" page?

**Comment by HarHarLinks** [comment]
I should mention:
```
ls 21ss/(VU) Spezielle Themen der Virtuellen Realität (VR II)/LessonExercise Recordings

Lesson01.mp4  Lesson_02___Applications_Trim.mp4  zoom_0_cut.mp4  zoom_0.mp4
```

I wouldn't be completely surprised if all other files are named `zoom_0[_cut]?.mp4` and thus assumed already downloaded... if so it would be nice if you can circumvent that.
zoom_0_cut.mp4 is Exercise 1, zoom_0.mp4 is Lesson 03.

<details>
<summary>expand (do you need more? these seem to be the relevant contents)</summary>

```
<div id="page" class="container-fluid d-print-block">



        <header id="page-header" class="row">
    <div class="col-12 pt-3 pb-3">
        <div class="card ">
            <div class="card-body ">
                
                <div class="d-flex">
                    <div class="mr-auto">
                        <div class="page-context-header"><div class="page-header-headings"><h1>Spezielle Themen der Virtuellen Realität (VR II) (VU) [21ss-12.53694]</h1></div></div>
                    </div>
                </div>
                <div class="d-flex flex-wrap">
                    <div id="page-navbar">
                        <nav role="navigation">
    <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="line-clamp" href="https://moodle.rwth-aachen.de/my/">Dashboard</a></li>
                <li class="breadcrumb-item">Meine Kurse</li>
                <li class="breadcrumb-item"><a class="line-clamp" href="https://moodle.rwth-aachen.de/course/view.php?id=14908" title="Spezielle Themen der Virtuellen Realität (VR II) (VU) [21ss-12.53694]">(VU) Spezielle Themen der Virtuellen Realität (VR II)</a></li>
                <li class="breadcrumb-item"><a class="line-clamp" href="https://moodle.rwth-aachen.de/course/view.php?id=14908">Kursinhalt</a></li>
                <li class="breadcrumb-item"><a class="line-clamp" href="https://moodle.rwth-aachen.de/course/view.php?id=14908#section-1">Lesson/Exercise Recordings</a></li>
                <li class="breadcrumb-item"><a class="line-clamp" href="https://moodle.rwth-aachen.de/mod/page/view.php?id=597175" title="Textseite">Lesson 01 - Introduction</a></li>
    </ol>
</nav>
                    </div>
                    <div class="ml-auto d-flex">
                        
                    </div>
                    <div id="course-header">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

        <div id="page-content" class="row pb-3 d-print-block">
            <div id="region-main-box" class="col-12">
                    
                    <div id="boost-campus-course-settings" class="card">
                        <div class="mx-2 pt-2">
                            <ul class="nav nav-tabs" role="tablist">
                            <!-- First the top most node and immediate children -->
                                <li class="nav-item">
                                    <a class="nav-link active" href="#course-settings-courseadmin" data-toggle="tab" role="tab">Kurs-Administration</a>
                                </li>
                            <!-- Now the first level children with sub nodes -->
                            </ul>
                    
                            <div class="tab-content">
                                <div class="tab-pane active" id="course-settings-courseadmin" role="tabpanel">
                                    <div class="card">
                                        <div class="card-body pb-0">
                                            <div class="row">
                                                <div class="col-sm-4">
                                                    
                                                    <h4>Kurs-Administration</h4>
                                                </div>
                                                <div class="col-sm-8">
                                                    <ul class="list-unstyled">
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <section id="region-main" aria-label="Inhalt">

                    <span class="notifications" id="user-notifications"></span>
                    <div role="main"><span id="maincontent"></span><h2>Lesson 01 - Introduction</h2><div class="box py-3 generalbox center clearfix"><div class="no-overflow"><p dir="ltr" style="text-align: left;">&nbsp;</p><div class="occontainer_outer">
  <div class="occontainer_inner">
    <iframe data-framesrc="https://engage.streaming.rwth-aachen.de/play/42fbd30a-4374-40ac-b2a5-ded4d9d3c907" class="ocplayer" allowfullscreen="true" src="https://engage.streaming.rwth-aachen.de/play/42fbd30a-4374-40ac-b2a5-ded4d9d3c907"></iframe>
  </div>
</div>&nbsp;<br><p></p></div></div><div class="modified">Zuletzt geändert: Montag, 26. April 2021, 08:03</div></div>
                    <div class="mt-5 mb-1 activity-navigation container-fluid">
<div class="row">
    <div class="col-md-4">        <div class="float-left">
                <a href="https://moodle.rwth-aachen.de/mod/organizer/view.php?id=625095&amp;forceview=1" id="prev-activity-link" class="btn btn-link" title="Oral Exam Appointments">◄ Oral Exam Appointments</a>

        </div>
</div>
    <div class="col-md-4">        <div class="mdl-align">
            <div class="urlselect">
    <form method="post" action="https://moodle.rwth-aachen.de/course/jumpto.php" class="form-inline" id="url_select_f60c20b1f9820416">
        <input type="hidden" name="sesskey" value="redacted">
            <label for="jump-to-activity" class="sr-only">
                Direkt zu:
            </label>
        <select id="jump-to-activity" class="custom-select urlselect" name="jump">
                    <option value="" selected="">Direkt zu:</option>
                    <option value="/mod/forum/view.php?id=504193&amp;forceview=1">Ankündigungen</option>
                    <option value="/mod/organizer/view.php?id=625095&amp;forceview=1">Oral Exam Appointments</option>
                    <option value="/mod/page/view.php?id=598698&amp;forceview=1">Lesson 02 - Applications</option>
                    <option value="/mod/page/view.php?id=603818&amp;forceview=1">Lesson 03 - Navigation Pt. 1</option>
                    <option value="/mod/page/view.php?id=604269&amp;forceview=1">Lesson 04 - Navigation Pt. 2</option>
                    <option value="/mod/page/view.php?id=609189&amp;forceview=1">Lesson 05 - Navigation Pt. 3</option>
                    <option value="/mod/page/view.php?id=620451&amp;forceview=1">Lesson 06 - Navigation Pt. 4</option>
                    <option value="/mod/page/view.php?id=621146&amp;forceview=1">Lesson 07 - Haptics Pt. 1</option>
                    <option value="/mod/page/view.php?id=631970&amp;forceview=1">Lesson 07 - Haptics Pt. 2 &amp; Exercise 02</option>
                    <option value="/mod/page/view.php?id=627682&amp;forceview=1">Lesson 08 - Audio Rendering</option>
                    <option value="/mod/page/view.php?id=633908&amp;forceview=1">Lesson 09 - Audio Rendering Pt. 2</option>
                    <option value="/mod/page/view.php?id=615466&amp;forceview=1">Exercise 1 - Navigation</option>
                    <option value="/mod/resource/view.php?id=608424&amp;forceview=1">Exercise 1</option>
                    <option value="/mod/resource/view.php?id=614780&amp;forceview=1">Exercise 1 - Solution</option>
                    <option value="/mod/resource/view.php?id=618172&amp;forceview=1">Exercise 2</option>
                    <option value="/mod/resource/view.php?id=631796&amp;forceview=1">Exercise 2 - Solution</option>
                    <option value="/mod/resource/view.php?id=631729&amp;forceview=1">Exercise 3</option>
                    <option value="/mod/resource/view.php?id=528038&amp;forceview=1">Organizational Stuff</option>
                    <option value="/mod/resource/view.php?id=528039&amp;forceview=1">Summary of VR I</option>
                    <option value="/mod/resource/view.php?id=528040&amp;forceview=1">Applications</option>
                    <option value="/mod/resource/view.php?id=528042&amp;forceview=1">Navigation in Virtual Environments</option>
                    <option value="/mod/resource/view.php?id=528044&amp;forceview=1">Haptics</option>
                    <option value="/mod/resource/view.php?id=528045&amp;forceview=1">Collision Detection</option>
                    <option value="/mod/resource/view.php?id=528046&amp;forceview=1">Audio Rendering</option>
                    <option value="/mod/resource/view.php?id=528047&amp;forceview=1">Acoustic VR</option>
                    <option value="/mod/resource/view.php?id=528056&amp;forceview=1">Virtual Humans</option>
                    <option value="/mod/resource/view.php?id=528048&amp;forceview=1">Experimental Design</option>
                    <option value="/mod/resource/view.php?id=528049&amp;forceview=1">Paper on Automatic Speed Adjustment [Freitag et al., 2017]</option>
                    <option value="/mod/resource/view.php?id=528050&amp;forceview=1">Cybersickness</option>
                    <option value="/mod/resource/view.php?id=528051&amp;forceview=1">Paper on Dynamic FoV Reduction [Zielasko et al., 2018]</option>
                    <option value="/mod/resource/view.php?id=528052&amp;forceview=1">Scientific Visualization - Part1</option>
                    <option value="/mod/resource/view.php?id=528053&amp;forceview=1">Scientific Visualization Part 2</option>
                    <option value="/mod/resource/view.php?id=528054&amp;forceview=1">Scientific Visualization Part3</option>
                    <option value="/mod/resource/view.php?id=528055&amp;forceview=1">Scientific Visualization Part4</option>
                    <option value="/mod/resource/view.php?id=528057&amp;forceview=1">Physics</option>
                    <option value="/mod/resource/view.php?id=528058&amp;forceview=1">Transformations in Computer Graphics</option>
                    <option value="/mod/resource/view.php?id=528059&amp;forceview=1">Everyday VR</option>
                    <option value="/mod/resource/view.php?id=528060&amp;forceview=1">An Industrial Usecase For VR</option>
        </select>
            <noscript>
                <input type="submit" class="btn btn-secondary ml-1" value="Start">
            </noscript>
    </form>
</div>

        </div>
</div>
    <div class="col-md-4">        <div class="float-right">
                <a href="https://moodle.rwth-aachen.de/mod/page/view.php?id=598698&amp;forceview=1" id="next-activity-link" class="btn btn-link" title="Lesson 02 - Applications">Lesson 02 - Applications ►</a>

        </div>
</div>
</div>
</div>
                    

                </section>
            </div>
        </div>
    </div>
```

</details>

**Comment by Romern** [comment]
Yes we need to adress https://github.com/Romern/syncMyMoodle/issues/35

**Comment by Romern** [comment]
Could you try https://github.com/Romern/syncMyMoodle/commit/ea17a29d741d5fca17f6175aeef5305bf4ce482e ?

**Comment by HarHarLinks** [comment]
Of course I spoke to soon, this broke something else:

```
Syncing (VO) Funktionale Programmierung...
Traceback (most recent call last):
  File "syncMyMoodle.py", line 600, in scanForLinks
    self.scanForLinks(response.text, parent_node, course_id, module_title=module_title, single=False)
  File "syncMyMoodle.py", line 621, in scanForLinks
    parent_node.add_child(f"{module_title}.mp4" or vid, vid, "Opencast", url=vid, additional_info=course_id)
  File "syncMyMoodle.py", line 48, in add_child
    name = base + base64.urlsafe_b64encode(str(id).encode("utf-8")) + ext
TypeError: can only concatenate str (not "bytes") to str
Error while downloading url https://moodle.rwth-aachen.de/pluginfile.php/1541497/mod_page/content/index.html?forcedownload=1: can only concatenate str (not "bytes") to str
```

**Comment by Romern** [comment]
that shoudl be fixed in https://github.com/Romern/syncMyMoodle/commit/9e1b03f11a8dfb27d7734403634b6bf6ed2a1515

**Comment by HarHarLinks** [comment]
Seems fixed.

Might I suggest, to use the upload date if possible as an identifier before or additional to resorting to base64 URL as ID?
Perhaps combining the earlier and new naming method? I know this is very nonstandard. I can provide dumps from all of my courses as examples if you want them.

I now have half a dozen
```
Videos from the Exercise CourseaHR0cHM6Ly9lbmdhZ2Uuc3RyZWFtaW5nLnJ3dGgtYWFjaGVuLmRlL3BsYXkvMTBiZGVhZjItNzJhMy00YTdhLTk5N2EtYTVjZmE0NzBjOTUw.mp4
```
which is better than not having them, but it would be nice to be able to identify which is which easily.

**Comment by Romern** [comment]
Seems reasonable, especially in cases like you mentioned. Ideally you could make a merge request with the changes.

**Comment by HarHarLinks** [comment]
https://github.com/Romern/syncMyMoodle/blob/9e1b03f11a8dfb27d7734403634b6bf6ed2a1515/syncMyMoodle.py#L621

I think `f"{module_title}.mp4" or vid` never hits `vid`, because the string is never False unless there is something I don't know about None in f-strings. That would be the reason I get the `None{base64}.mp4` videos where they were formerly named properly.

I have a PR cooking that should achieve what I suggested once it's finished.

**Comment by Romern** [comment]
good catch, I fixed that in https://github.com/Romern/syncMyMoodle/commit/c0a0b5f3021f025d740a6e2771cb1a1b6413efbf
